//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string BookingID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Status { get; set; }
        public bool IsAllDay { get; set; }
        public Nullable<int> RecurrenceID { get; set; }
        public string StartTimeZone { get; set; }
        public string EndTimeZone { get; set; }
        public string RecurrenceRule { get; set; }
        public string RecurrenceException { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Recurrence Recurrence { get; set; }
        public virtual Room Room { get; set; }
    }
}
